[package]
name = "osmium-package"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
osmium-core = { path = "../osmium-core" }
serde_json.workspace = true
unicode-normalization.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
