[workspace]
members = ["apps/desktop/src-tauri", "crates/osmium-cli", "crates/osmium-core", "crates/osmium-package", "crates/osmium-store"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
publish = false

[workspace.dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "=1.0.151", features = ["float_roundtrip"] }
clap = { version = "4.5.46", features = ["derive"] }
jsonschema = { version = "0.56.0", default-features = false }
unicode-normalization = "0.1.25"
language-tags = "0.3.2"
tempfile = "3.27.0"
sha2 = "0.11.0"
fs2 = "0.4.3"
rusqlite = { version = "0.40.2", default-features = false, features = ["bundled", "backup"] }
uuid = { version = "1.26.1", features = ["v4"] }
time = { version = "0.3.45", features = ["formatting"] }
zip = { version = "6.0.0", default-features = false, features = ["deflate-flate2-zlib-rs"] }
yaml-rust2 = { version = "0.13.0", default-features = false }
pulldown-cmark = { version = "0.13.4", default-features = false }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
